"""Category table

Revision ID: 0aa512836d3d
Revises: 531c818e7d99
Create Date: 2018-11-18 03:07:31.651934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa512836d3d'
down_revision = '531c818e7d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('remaining', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'remaining')
    # ### end Alembic commands ###
