"""Account table

Revision ID: 22e7e5444de1
Revises: bdaa32cd8d23
Create Date: 2018-11-18 01:14:08.995867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e7e5444de1'
down_revision = 'bdaa32cd8d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('accType', sa.String(length=128), nullable=True))
    op.add_column('account', sa.Column('nickname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'nickname')
    op.drop_column('account', 'accType')
    # ### end Alembic commands ###
